import { describe, it, expect } from 'vitest';
import {
  validateFile,
  validateGeneratedFiles,
  formatValidationWarnings,
} from './validation';

// ── validateFile ─────────────────────────────────────────────────────

describe('validateFile', () => {
  // TypeScript validation

  it('passes valid TypeScript code', () => {
    const result = validateFile('src/routes/health.ts', [
      'import { Hono } from "hono";',
      '',
      'const health = new Hono();',
      'health.get("/", (c) => c.json({ ok: true }));',
      'export { health };',
    ].join('\n'));
    expect(result.ok).toBe(true);
    expect(result.warnings).toHaveLength(0);
  });

  it('detects unbalanced curly braces', () => {
    const result = validateFile('src/index.ts', 'function foo() {\n  return 1;\n');
    expect(result.ok).toBe(false);
    expect(result.warnings).toContain('Unbalanced curly braces {}');
  });

  it('detects unbalanced parentheses', () => {
    const result = validateFile('src/index.ts', 'console.log("hello"\n');
    expect(result.ok).toBe(false);
    expect(result.warnings).toContain('Unbalanced parentheses ()');
  });

  it('detects unbalanced square brackets', () => {
    const result = validateFile('src/index.ts', 'const arr = [1, 2, 3\n');
    expect(result.ok).toBe(false);
    expect(result.warnings).toContain('Unbalanced square brackets []');
  });

  it('ignores brackets inside strings', () => {
    const code = 'const x = "{ not a brace }";\nconst y = `[template ${1}]`;';
    const result = validateFile('src/foo.ts', code);
    expect(result.ok).toBe(true);
  });

  it('ignores brackets inside comments', () => {
    const code = [
      '// { this is a comment',
      '/* [block comment] */',
      'const x = 1;',
    ].join('\n');
    const result = validateFile('src/foo.ts', code);
    expect(result.ok).toBe(true);
  });

  it('detects eval() usage', () => {
    const result = validateFile('src/bad.ts', 'const result = eval("1+1");\nexport { result };');
    expect(result.ok).toBe(false);
    expect(result.warnings).toContain('Contains eval() — forbidden by project rules');
  });

  it('detects `any` type annotation', () => {
    const result = validateFile('src/bad.ts', 'function foo(x: any) { return x; }');
    expect(result.ok).toBe(false);
    expect(result.warnings).toContain('Contains `any` type — use proper typing or `unknown`');
  });

  it('detects `as any` cast', () => {
    const result = validateFile('src/bad.ts', 'const x = value as any;');
    expect(result.ok).toBe(false);
    expect(result.warnings).toContain('Contains `any` type — use proper typing or `unknown`');
  });

  it('detects empty file', () => {
    const result = validateFile('src/empty.ts', '');
    expect(result.ok).toBe(false);
    expect(result.warnings).toContain('File is empty');
  });

  it('detects stub-only content', () => {
    const result = validateFile('src/stub.ts', '// TODO: Implement\n// Generated by Dream Machine Build\n\nexport {};\n');
    expect(result.ok).toBe(false);
    expect(result.warnings).toContain('File contains only stub/TODO content — no real implementation');
  });

  // SQL validation

  it('passes valid SQL', () => {
    const result = validateFile('migrations/001.sql', 'CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY);');
    expect(result.ok).toBe(true);
  });

  it('warns on DROP TABLE without IF EXISTS', () => {
    const result = validateFile('migrations/drop.sql', 'DROP TABLE users;');
    expect(result.ok).toBe(false);
    expect(result.warnings).toContain('DROP TABLE without IF EXISTS — potential data loss');
  });

  it('allows DROP TABLE with IF EXISTS', () => {
    const result = validateFile('migrations/drop.sql', 'DROP TABLE IF EXISTS users;');
    expect(result.ok).toBe(true);
  });

  it('warns on SQL file with no SQL keywords', () => {
    const result = validateFile('migrations/empty.sql', '-- Just a comment\n');
    expect(result.ok).toBe(false);
    expect(result.warnings).toContain('No SQL statements found (expected CREATE, ALTER, INSERT, etc.)');
  });

  // Docs skip

  it('skips validation for docs/ files', () => {
    const result = validateFile('docs/dream-specs/my-spec.md', '');
    expect(result.ok).toBe(true);
    expect(result.warnings).toHaveLength(0);
  });

  // TSX validation

  it('passes valid TSX component', () => {
    const code = [
      'import React from "react";',
      '',
      'interface Props { name: string; }',
      '',
      'export default function Greeting({ name }: Props) {',
      '  return <div>Hello, {name}</div>;',
      '}',
    ].join('\n');
    const result = validateFile('src/components/greeting.tsx', code);
    expect(result.ok).toBe(true);
  });

  it('handles escaped quotes in strings correctly', () => {
    const code = 'const x = "escaped \\" quote";\nconst y = 1;';
    const result = validateFile('src/foo.ts', code);
    expect(result.ok).toBe(true);
  });
});

// ── validateGeneratedFiles ──────────────────────────────────────────

describe('validateGeneratedFiles', () => {
  it('passes when all files are valid', () => {
    const files = [
      { path: 'docs/spec.md', content: '# Spec' },
      { path: 'src/index.ts', content: 'export const x = 1;' },
    ];
    const { passed, results } = validateGeneratedFiles(files);
    expect(passed).toBe(true);
    expect(results).toHaveLength(2);
    expect(results.every(r => r.ok)).toBe(true);
  });

  it('fails when any file has warnings', () => {
    const files = [
      { path: 'src/good.ts', content: 'export const x = 1;' },
      { path: 'src/bad.ts', content: '' },
    ];
    const { passed, results } = validateGeneratedFiles(files);
    expect(passed).toBe(false);
    expect(results[0].ok).toBe(true);
    expect(results[1].ok).toBe(false);
  });

  it('returns empty results for empty input', () => {
    const { passed, results } = validateGeneratedFiles([]);
    expect(passed).toBe(true);
    expect(results).toHaveLength(0);
  });
});

// ── formatValidationWarnings ────────────────────────────────────────

describe('formatValidationWarnings', () => {
  it('returns empty string when all pass', () => {
    const results = [
      { path: 'src/ok.ts', ok: true, warnings: [] },
    ];
    expect(formatValidationWarnings(results)).toBe('');
  });

  it('formats warnings as markdown', () => {
    const results = [
      { path: 'src/bad.ts', ok: false, warnings: ['Unbalanced curly braces {}', 'Contains `any` type — use proper typing or `unknown`'] },
      { path: 'src/ok.ts', ok: true, warnings: [] },
    ];
    const output = formatValidationWarnings(results);
    expect(output).toContain('### Validation Warnings');
    expect(output).toContain('`src/bad.ts`');
    expect(output).toContain('Unbalanced curly braces');
    expect(output).toContain('`any`');
    expect(output).not.toContain('src/ok.ts');
    expect(output).toContain('Manual review recommended');
  });

  it('includes multiple failing files', () => {
    const results = [
      { path: 'src/a.ts', ok: false, warnings: ['Warning A'] },
      { path: 'src/b.ts', ok: false, warnings: ['Warning B'] },
    ];
    const output = formatValidationWarnings(results);
    expect(output).toContain('`src/a.ts`');
    expect(output).toContain('`src/b.ts`');
  });
});
